import "~/styles/globals.css";
import { Inter } from "next/font/google";
import TopNavbar from "~/components/core/navbar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "T3 Gallery Clone - Using T3 Stack",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`font-sans ${inter.variable} flex flex-col gap-4`}>
          <TopNavbar />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
